apiVersion: v1
kind: Namespace
metadata:
  name: example-webserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-webserver
  namespace: example-webserver
  labels:
    application-scope: example

spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-webserver
  template:
    metadata:
      labels:
        app: example-webserver
        application-scope: example
    spec:
      containers:
      - name: example-webserver
        image: algatux/example-webserver:v0.1.3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: example-webserver
  namespace: example-webserver
spec:
  selector:
    app: example-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
